from .update_dashboard_task import UpdateDashboardTask
from .fetch_covid19_india_data_task import FetchCovid19IndiaDataTask
from .fetch_ward_data import FetchWardDataTask
from .updateEpiStatsRepo_task import UpdateEpiStatsTask
